// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssxjcdczdynocbmygnwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzeGpjZGN6ZHlub2NibXlnbnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDg2MTMsImV4cCI6MjA3MjQ4NDYxM30.-FtqJ_iPM5izCFbZGXf4bK7B4CevVLCInlssWcm0ze4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});